# templates configuration file (TOML)

output_file = "templates/templates.go"
package_name = "templates"

# folder = "/home/mau/Code/go/src/github.com/mmbros/music-arc/templates"
folder = "templates/music-arc"

# page_enum_type = "PageEnum"
page_enum_prefix = "Page"
# page_enum_suffix = "Suffix"

# name of the variable used as funcMap.
# The variable must be defined in another file of the same package (es. "templates/func-map.go")
# in not defined or blank, no funcMap will be used
func_map = "funcMap"

[templates]
bs = ["_browser-sync.tmpl"]

part_artists = ["partials/artists-list.tmpl"]
part_artist = ["partials/artist.tmpl"]
part_album = ["partials/album.tmpl"]
part_playlists = ["partials/playlists-list.tmpl"]
part_playlist = ["partials/playlist.tmpl"]

## Sito
base = ["_base.tmpl", "bs"]
artists_list = ["base", "part_artists", "artists-list.tmpl" ]
artist = ["base", "part_artists", "part_artist", "artist.tmpl"]
album = ["base", "part_artist", "part_album", "album.tmpl"]
playlists_list = ["base", "part_playlists", "playlists-list.tmpl" ]
playlist= ["base", "part_playlists", "part_playlist", "playlist.tmpl" ]

album_list = ["base", "album-list.tmpl"]

## Cover
cover_base = ["cover/_base.tmpl", "bs"]
cover_front = ["cover_base", "cover/front.tmpl" ]
cover_front_10 = ["cover_base", "cover/front-10.tmpl" ]


[pages]
Album = {template="album"}
AlbumList = {template="album_list"}
Artist = {template="artist"}
ArtistsList = {template="artists_list"}
PlaylistsList = {template="playlists_list"}
Playlist = {template="playlist"}

CoverFront = {template="cover_front"}
CoverFront10 = {template="cover_front_10"}
